name: Gh-Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Create .env file in web_static
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > ./web_static/.env
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      - name: Deploy static files
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web_static
          keep_files: true  # Set to true to retain files not in the current deployment
      - name: Configure custom domain
        run: |
          mkdir -p web_static
          echo "hyunjaemoon.com" > web_static/CNAME
          cat web_static/CNAME
        env:
          your-custom-domain: hyunjaemoon.com
