name: Gh-Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: erickzanardo/flutter-gh-pages@v7
        with:
          customArgs: --dart-define GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} # Add this line
          basehref: /flutter-github-page/
      - name: Configure custom domain
        run: |
          echo "hyunjaemoon.com" > CNAME
          cat CNAME
        env:
          your-custom-domain: hyunjaemoon.com
